# Site settings
title: Dimension
email: ghilee-lucian@hotmail.com
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "/dimension-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 6 Al 
city: N
state: HD
zip_code: 5531009
country: Romania
phone: (716) -1523

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: https://gitlab.com
googleplus_url: https://plus.google.com
instagram_url:
linkedin_url: https://www.linkedin.com
pinterest_url:
slack_url:
twitter_url: https://twitter.com

# Build settings
markdown: kramdown

sass:
style: compressed
